In [ ]:
%pip install yfinance pandas

In [7]:

import yfinance as yf
import pandas as pd

In [4]:

# Descargar datos históricos del IBEX 35 desde 2020-01-01 hasta hoy
# ibex = yf.download("^IBEX", start="2020-01-01", end="2025-08-14", interval="1d")

# Guardar en CSV
# ibex.to_csv("ibex35_2020_2025.csv", encoding="utf-8")

# print("CSV generado: ibex35_2020_2025.csv")

In [74]:
ibex = pd.read_csv("ibex35_2020_2025.csv")

In [75]:
ibex.head()

         Date        Close         High          Low         Open     Volume
0  2020-01-02  9691.200195  9705.400391  9615.099609  9639.099609  142379600
1  2020-01-03  9646.599609  9650.700195  9581.200195  9631.200195  135130000
2  2020-01-06  9600.900391  9618.200195  9492.700195  9585.400391  103520400
3  2020-01-07  9579.799805  9657.900391  9557.900391  9623.099609  133476100
4  2020-01-08  9591.400391  9604.299805  9520.299805  9535.099609  133957600

In [76]:
ibex['Date'] = pd.to_datetime(ibex['Date'])
ibex.set_index('Date', inplace=True)

In [77]:
ibex.head()

                  Close         High          Low         Open     Volume
Date
2020-01-02  9691.200195  9705.400391  9615.099609  9639.099609  142379600
2020-01-03  9646.599609  9650.700195  9581.200195  9631.200195  135130000
2020-01-06  9600.900391  9618.200195  9492.700195  9585.400391  103520400
2020-01-07  9579.799805  9657.900391  9557.900391  9623.099609  133476100
2020-01-08  9591.400391  9604.299805  9520.299805  9535.099609  133957600

In [78]:
ibex.dtypes

Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [79]:
ibex = pd.read_csv("ibex35_2020_2025.csv", parse_dates=["Date"], index_col="Date")

In [80]:
ibex.head()

                  Close         High          Low         Open     Volume
Date
2020-01-02  9691.200195  9705.400391  9615.099609  9639.099609  142379600
2020-01-03  9646.599609  9650.700195  9581.200195  9631.200195  135130000
2020-01-06  9600.900391  9618.200195  9492.700195  9585.400391  103520400
2020-01-07  9579.799805  9657.900391  9557.900391  9623.099609  133476100
2020-01-08  9591.400391  9604.299805  9520.299805  9535.099609  133957600

In [81]:
ibex.shape

(1438, 5)

In [87]:
ibex.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1438 entries, 2020-01-02 to 2025-08-13
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   1438 non-null   float64
 1   High    1438 non-null   float64
 2   Low     1438 non-null   float64
 3   Open    1438 non-null   float64
 4   Volume  1438 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 99.7 KB

In [91]:
# Un valor concreto
ibex250602 = ibex.loc['2025-06-02']
ibex250602

Close     1.420280e+04
High      1.423440e+04
Low       1.409960e+04
Open      1.410590e+04
Volume    8.979400e+07
Name: 2025-06-02 00:00:00, dtype: float64

In [ ]:
# Todos los valores de un mes
ibex2506 = ibex.loc['2025-06']
ibex2506.head()

                   Close          High           Low          Open     Volume
Date
2025-06-02  14202.799805  14234.400391  14099.599609  14105.900391   89794000
2025-06-03  14128.400391  14249.200195  14080.500000  14239.599609  104041400
2025-06-04  14101.299805  14185.200195  14036.400391  14175.799805  101954800
2025-06-05  14203.700195  14204.900391  14038.299805  14082.299805   98898900
2025-06-06  14247.599609  14286.099609  14179.099609  14193.700195   78318000

In [69]:
# Todos los valores de un año
ibex25 = ibex.loc['2025']
ibex25.shape

(157, 5)

In [93]:
ibex25.index.is_quarter_end

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [94]:
ibex25.loc[ibex25.index.is_quarter_end]

                   Close          High           Low          Open     Volume
Date
2025-03-31  13135.400391  13249.799805  13051.799805  13224.599609  167060300
2025-06-30  13991.900391  14029.099609  13894.400391  14025.599609  110470200

In [99]:
ibex25.index.month, ibex25.index.year

(Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        ...
        7, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       dtype='int32', name='Date', length=157),
 Index([2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025,
        ...
        2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025],
       dtype='int32', name='Date', length=157))

In [65]:
ibex24 = ibex['2024-01-01 00:00':'2025-01-01 00:00']
ibex24.shape

(256, 5)

In [66]:
media_mensual = ibex24.resample('M').mean()
media_mensual.head()

C:\Users\aitor\AppData\Local\Temp\ipykernel_39812\3453771284.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  media_mensual = ibex24.resample('M').mean()

,Close,High,Low,Open,Volume
Date,,,,,
2024-01-31,10016.259011,10069.972701,9957.822665,10020.490945,1.312984e+08
2024-02-29,10003.104771,10053.933315,9961.880999,10014.028506,1.414177e+08
2024-03-31,10571.425049,10605.965039,10504.600000,10521.364941,1.776267e+08
2024-04-30,10870.609561,10942.638021,10807.738281,10880.161877,1.746393e+08
2024-05-31,11199.186346,11236.586337,11134.386364,11178.250044,1.707392e+08

In [20]:
media_mensual.agg(['mean', 'min', 'max'])

             Close          High           Low          Open        Volume
mean  11044.879507  11099.089394  10982.163324  11039.518731  1.316156e+08
min   10003.104771  10053.933315   9957.822665  10014.028506  9.708670e+07
max   11783.330460  11838.421748  11717.534774  11784.673998  1.776267e+08

In [21]:
media_mensual['Close_lag'] = media_mensual['Close'].shift(1)
media_mensual['Close_lead'] = media_mensual['Close'].shift(-1)
media_mensual.head()

,Close,High,Low,Open,Volume,Close_lag,Close_lead
Date,,,,,,,
2024-01-31,10016.259011,10069.972701,9957.822665,10020.490945,1.312984e+08,NaN,10003.104771
2024-02-29,10003.104771,10053.933315,9961.880999,10014.028506,1.414177e+08,10016.259011,10571.425049
2024-03-31,10571.425049,10605.965039,10504.600000,10521.364941,1.776267e+08,10003.104771,10870.609561
2024-04-30,10870.609561,10942.638021,10807.738281,10880.161877,1.746393e+08,10571.425049,11199.186346
2024-05-31,11199.186346,11236.586337,11134.386364,11178.250044,1.707392e+08,10870.609561,11160.760059

In [25]:
media_movil = media_mensual.rolling(window=3).mean()

In [26]:
media_movil.head()

,Close,High,Low,Open,Volume,Close_lag,Close_lead
Date,,,,,,,
2024-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-03-31,10196.929610,10243.290351,10141.434555,10185.294797,1.501143e+08,NaN,10481.713127
2024-04-30,10481.713127,10534.178792,10424.739760,10471.851775,1.645612e+08,10196.929610,10880.406985
2024-05-31,10880.406985,10928.396466,10815.574882,10859.925621,1.743351e+08,10481.713127,11076.851988

In [49]:
media_filled = media_mensual.interpolate(method="linear", limit_direction='both')
media_filled.head(3)

,Close,High,Low,Open,Volume,Close_lag,Close_lead
Date,,,,,,,
2024-01-31,10016.259011,10069.972701,9957.822665,10020.490945,1.312984e+08,10016.259011,10003.104771
2024-02-29,10003.104771,10053.933315,9961.880999,10014.028506,1.414177e+08,10016.259011,10571.425049
2024-03-31,10571.425049,10605.965039,10504.600000,10521.364941,1.776267e+08,10003.104771,10870.609561