# Proyecto Series Temporales

## 1. Cargando los datos

In [1]:
import pandas as pd

# Cargamos los datos
df_temperatura = pd.read_csv("ts_temp_20170201_20200131.csv")
df_energia = pd.read_csv("ts_load_metered_20170201_20200131.csv")

In [2]:
df_temperatura.head()

,STATION,DATE,REPORT_TYPE,SOURCE,HourlyDryBulbTemperature
0,72520514762,2017-02-01T00:53:00,FM-15,7,37.0
1,72520514762,2017-02-01T01:53:00,FM-15,7,37.0
2,72520514762,2017-02-01T02:53:00,FM-15,7,36.0
3,72520514762,2017-02-01T03:53:00,FM-15,7,36.0
4,72520514762,2017-02-01T04:53:00,FM-15,7,36.0

In [3]:
# Pasamos el campo DATE a datetime
df_temperatura['DATE'] = pd.to_datetime(df_temperatura['DATE'])

In [4]:
df_energia.head()

,datetime_beginning_utc,datetime_beginning_ept,nerc_region,mkt_region,zone,load_area,mw,is_verified
0,2/1/2017 5:00,2/1/2017 0:00,RFC,WEST,DUQ,DUQ,1419.881,True
1,2/1/2017 6:00,2/1/2017 1:00,RFC,WEST,DUQ,DUQ,1379.505,True
2,2/1/2017 7:00,2/1/2017 2:00,RFC,WEST,DUQ,DUQ,1366.106,True
3,2/1/2017 8:00,2/1/2017 3:00,RFC,WEST,DUQ,DUQ,1364.453,True
4,2/1/2017 9:00,2/1/2017 4:00,RFC,WEST,DUQ,DUQ,1391.265,True

In [5]:
# Pasamos el campo datetime_beginning_ept a datetime
df_energia['datetime_beginning_ept'] = pd.to_datetime(df_temperatura['DATE'])

In [6]:
# Unimos los datos por fecha
df_merged = pd.merge(df_energia, df_temperatura, left_on='datetime_beginning_ept', right_on='DATE')
df_merged.head()

,datetime_beginning_utc,datetime_beginning_ept,nerc_region,mkt_region,zone,load_area,mw,is_verified,STATION,DATE,REPORT_TYPE,SOURCE,HourlyDryBulbTemperature
0,2/1/2017 5:00,2017-02-01 00:53:00,RFC,WEST,DUQ,DUQ,1419.881,True,72520514762,2017-02-01 00:53:00,FM-15,7,37.0
1,2/1/2017 6:00,2017-02-01 01:53:00,RFC,WEST,DUQ,DUQ,1379.505,True,72520514762,2017-02-01 01:53:00,FM-15,7,37.0
2,2/1/2017 7:00,2017-02-01 02:53:00,RFC,WEST,DUQ,DUQ,1366.106,True,72520514762,2017-02-01 02:53:00,FM-15,7,36.0
3,2/1/2017 8:00,2017-02-01 03:53:00,RFC,WEST,DUQ,DUQ,1364.453,True,72520514762,2017-02-01 03:53:00,FM-15,7,36.0
4,2/1/2017 9:00,2017-02-01 04:53:00,RFC,WEST,DUQ,DUQ,1391.265,True,72520514762,2017-02-01 04:53:00,FM-15,7,36.0

In [7]:
df = df_merged[["DATE", "mw", "HourlyDryBulbTemperature"]]
df.columns = ["fecha", "mw", "temperatura"]

df.head()

                fecha        mw  temperatura
0 2017-02-01 00:53:00  1419.881         37.0
1 2017-02-01 01:53:00  1379.505         37.0
2 2017-02-01 02:53:00  1366.106         36.0
3 2017-02-01 03:53:00  1364.453         36.0
4 2017-02-01 04:53:00  1391.265         36.0

In [8]:
# Otra forma
columnas = {'fecha': df_temperatura['DATE'], 'mw': df_energia['mw'], 'temp': df_temperatura['HourlyDryBulbTemperature'], }

In [9]:
df = pd.DataFrame(columnas)
df.head()

                fecha        mw  temp
0 2017-02-01 00:53:00  1419.881  37.0
1 2017-02-01 01:53:00  1379.505  37.0
2 2017-02-01 02:53:00  1366.106  36.0
3 2017-02-01 03:53:00  1364.453  36.0
4 2017-02-01 04:53:00  1391.265  36.0

## 2. Columnas con campos hora, dia, semana, mes y año

In [10]:
df['hora'] = pd.DatetimeIndex(df['fecha']).hour
df['dia'] = pd.DatetimeIndex(df['fecha']).day
df['diasemana'] = pd.DatetimeIndex(df['fecha']).dayofweek
df['mes'] = pd.DatetimeIndex(df['fecha']).month
df['anyo'] = pd.DatetimeIndex(df['fecha']).year

df.head()

                fecha        mw  temp  hora  dia  diasemana  mes  anyo
0 2017-02-01 00:53:00  1419.881  37.0     0    1          2    2  2017
1 2017-02-01 01:53:00  1379.505  37.0     1    1          2    2  2017
2 2017-02-01 02:53:00  1366.106  36.0     2    1          2    2  2017
3 2017-02-01 03:53:00  1364.453  36.0     3    1          2    2  2017
4 2017-02-01 04:53:00  1391.265  36.0     4    1          2    2  2017

In [11]:
df = df.set_index('fecha')
df.head()

                           mw  temp  hora  dia  diasemana  mes  anyo
fecha
2017-02-01 00:53:00  1419.881  37.0     0    1          2    2  2017
2017-02-01 01:53:00  1379.505  37.0     1    1          2    2  2017
2017-02-01 02:53:00  1366.106  36.0     2    1          2    2  2017
2017-02-01 03:53:00  1364.453  36.0     3    1          2    2  2017
2017-02-01 04:53:00  1391.265  36.0     4    1          2    2  2017

## 3. Comprueba las temperaturas y rellena los huecos

In [12]:
# Comprobamos si hay valores nulos en la columna de la temperatura
sum(df['temp'].isnull())

37

In [13]:
df['temp'] = df['temp'].interpolate(method='linear')

In [14]:
# Comprobamos de nuevo
sum(df['temp'].isnull())

0

## 4. Separamos el dataset

In [15]:
train = pd.DataFrame(df['2017-01-01':'2019-12-31'])
test = pd.DataFrame(df['2020-01-01':'2020-01-31'])

In [16]:
train.head()

                           mw  temp  hora  dia  diasemana  mes  anyo
fecha
2017-02-01 00:53:00  1419.881  37.0     0    1          2    2  2017
2017-02-01 01:53:00  1379.505  37.0     1    1          2    2  2017
2017-02-01 02:53:00  1366.106  36.0     2    1          2    2  2017
2017-02-01 03:53:00  1364.453  36.0     3    1          2    2  2017
2017-02-01 04:53:00  1391.265  36.0     4    1          2    2  2017

In [17]:
test.head()

                           mw  temp  hora  dia  diasemana  mes  anyo
fecha
2020-01-01 00:53:00  1363.428  31.0     0    1          2    1  2020
2020-01-01 01:53:00  1335.975  29.0     1    1          2    1  2020
2020-01-01 02:53:00  1296.817  30.0     2    1          2    1  2020
2020-01-01 03:53:00  1288.403  30.0     3    1          2    1  2020
2020-01-01 04:53:00  1292.263  31.0     4    1          2    1  2020

In [ ]:
%pip install fastparquet

In [20]:
## Persistimos el DataFrame
train.to_parquet("ts-train.parquet")
test.to_parquet("ts-test.parquet")